app:
    abs_path: /var/www/newwebiny/projects/weby.io/app/
    web_path: http://weby.loc/
    public_html: /var/www/newwebiny/projects/weby.io/public_html/
    theme_path: /var/www/newwebiny/projects/weby.io/public_html/theme/
    storage_abs_path: /var/www/newwebiny/projects/weby.io/public_html/storage/
    storage_web_path: http://weby.loc/storage/
    default_class: '\App\Handlers\PagesHandler'
    default_method: page404

database:
    name: postgres
    user: root
    password: 'paveL!'
    host: localhost