app:
    abs_path: /var/www/newwebiny/projects/weby.io/app/
    web_path: http://weby.com/
    public_html: /var/www/newwebiny/projects/weby.io/public_html/
    theme_abs_path: /var/www/newwebiny/projects/weby.io/public_html/theme/
    theme_web_path: http://weby.com/theme/
    storage_abs_path: /var/www/newwebiny/projects/weby.io/public_html/uploads/
    storage_web_path: http://weby.com/uploads/
    default_class: '\App\Handlers\PagesHandler'
    default_method: page404
    mode: development
    content_validators: #will be randomly switched by the app
        - http://mrcina.ath.cx:8080

database:
    name: postgres
    user: root
    password: 'paveL!'
    host: localhost