app:
    abs_path: /www/webiny/projects/weby.io/app/
    web_path: http://pavel910.homeftp.net/
    public_html: /www/webiny/projects/weby.io/public_html/
    theme_abs_path: /www/webiny/projects/weby.io/public_html/theme/
    theme_web_path: http://pavel910.homeftp.net/theme/
    storage_abs_path: /www/webiny/projects/weby.io/public_html/storage/
    storage_web_path: http://pavel910.homeftp.net/storage/
    default_class: '\App\Handlers\PagesHandler'
    default_method: page404
    mode: development
    content_validators: #will be randomly switched by the app
        - http://mrcina.ath.cx:8080
    tag_finders: #will be randomly switched by the app
        - http://mrcina.ath.cx:8085
    weby_searchers:
        - http://mrcina.ath.cx:8085
    node_geo_ip: udp://weby.com:8086

varnish:
    enabled: false
    flush_weby: 'curl --silent -X BAN "{webyUrl}" > /dev/null 2>&1'

screenshots:
    enabled: false
    ip: [192.168.1.11, 127.0.0.1]
    dimensions:
        dashboard: [90, 81]
        frontend_square: [215, 180]
        frontend_vertical: [215, 512]
        frontend_horizontal: [515, 180]
        open_graph: [398, 208]

database:
    name: weby.io
    user: root
    password: 'paveL!'
    host: localhost

caching_ttl: # TTL times for caches (in seconds)
    - social_share_counts: 5

images:
    dashboard: http://pavel910.homeftp.net/theme/images/default/my-weby.jpg
    original_screenshot: http://pavel910.homeftp.net/theme/images/default/my-weby.jpg
    frontend_square: http://pavel910.homeftp.net/theme/images/default/frontend_square.jpg
    frontend_vertical: http://pavel910.homeftp.net/theme/images/default/frontend_vertical.jpg
    frontend_horizontal: http://pavel910.homeftp.net/theme/images/default/frontend_horizontal.jpg
    open_graph: http://pavel910.homeftp.net/theme/images/default/open_graph.jpg

other:
    user_inactive_period: 5 #Sets the number of days which need to pass from users last sign in to proclaim him as inactive

feedback_receivers: # Email addresses for every feedback type
    general: [adrian1358@gmail.com]
    bugs: [pavel@webiny.com, adrian@webiny.com]