app:
    abs_path: /var/www/newwebiny/projects/weby.io/app/
    web_path: http://weby.com/
    public_html: /var/www/newwebiny/projects/weby.io/public_html/
    theme_abs_path: /var/www/newwebiny/projects/weby.io/public_html/theme/
    theme_web_path: http://weby.com/theme/
    storage_abs_path: /var/www/newwebiny/projects/weby.io/public_html/uploads/
    storage_web_path: http://weby.com/uploads/
    default_class: '\App\Handlers\PagesHandler'
    default_method: page404
    mode: development
    content_validators: #will be randomly switched by the app
        - http://weby.com:9005

database:
    name: postgres
    user: root
    password: 'paveL!'
    host: localhost

caching_ttl: # TTL times for caches (in seconds)
    - social_share_counts: 5

images:
    dashboard: http://weby.com/theme/images/default/my-weby.jpg
    original_screenshot: http://weby.com/theme/images/default/my-weby.jpg

other:
    user_inactive_period: 5 #Sets the number of days which need to pass from users last sign in to proclaim him as inactive

feedback_receivers: # Email addresses for every feedback type
    general: [adrian1358@gmail.com]
    bugs: [pavel@webiny.com, adrian@webiny.com]

disabled_tools: [flicker, slideshare]
