app:
    abs_path: /www/webiny/projects/weby.io/app/
    web_path: http://mrcina.ath.cx/weby.io/
    public_html: /www/webiny/projects/weby.io/public_html/
    theme_abs_path: /www/webiny/projects/weby.io/public_html/theme/
    theme_web_path: http://mrcina.ath.cx/weby.io/theme/
    storage_abs_path: /www/webiny/projects/weby.io/public_html/storage/
    storage_web_path: http://mrcina.ath.cx/weby.io/storage/
    default_class: '\App\Handlers\PagesHandler'
    default_method: page404
    mode: development

database:
    name: postgres
    user: root
    password: 'paveL!'
    host: localhost