routes:
    - ['', \App\Handlers\PagesHandler, index]
    - ['about', \App\Handlers\PagesHandler, about]
    - ['security/check-logged-user', \App\Handlers\UsersHandler, checkUserExists]
    - ['editor/save', \App\Handlers\EditorHandler, save]
    - ['embed/linkedin', \App\Handlers\EmbedHandler, linkedin]
    - ['embed/vine', \App\Handlers\EmbedHandler, vine]
    - ['embed/pinterest', \App\Handlers\EmbedHandler, pinterest]
    - ['link/parse', \App\Handlers\LinksHandler, parse]
    - ['/^([a-z0-9_-]*)\/([a-z0-9_-]*)\/([a-z0-9]*)$/', \App\Handlers\PagesHandler, viewWeby] #frontend Weby
    - ['/^([a-z0-9_-]*)\/([a-z0-9]*)$/', \App\Handlers\EditorHandler, route] #backend editor router
    - ['/^([a-z0-9_-]*)$/', \App\Handlers\EditorHandler, route] #backend editor router