routes:
    - ['', \App\Handlers\PagesHandler, index]
    - ['editor/templates', \App\Handlers\EditorHandler, templates]
    - ['editor', \App\Handlers\EditorHandler, index]
    - ['embed/linkedin', \App\Handlers\EmbedHandler, linkedin]
    - ['embed/prezi', \App\Handlers\EmbedHandler, prezi]
    - ['links/get', \App\Handlers\LinksHandler, getLink]
    - [database, \App\Handlers\TestHandler, index]