routes:
    - ['', \App\Handlers\PagesHandler, index]
    - ['about', \App\Handlers\PagesHandler, about]
    - ['security/check-logged-user', \App\Handlers\UsersHandler, checkUserExists]
    - ['editor/save', \App\Handlers\EditorHandler, save]
    - ['editor/create', \App\Handlers\EditorHandler, create]
    - ['editor/dashboard', \App\Handlers\EditorHandler, dashboard]
    - ['editor/upload-image', \App\Handlers\EditorHandler, uploadImage]
    - ['editor/remove-image', \App\Handlers\EditorHandler, removeImage]
    - ['embed/linkedin', \App\Handlers\EmbedHandler, linkedin]
    - ['embed/vine', \App\Handlers\EmbedHandler, vine]
    - ['embed/pinterest', \App\Handlers\EmbedHandler, pinterest]
    - ['embed/fb-post', \App\Handlers\EmbedHandler, fbPost]
    - ['link/parse', \App\Handlers\LinksHandler, parse]
    - ['/^([a-z0-9_-]*)\/([a-z0-9_-]*)\/([a-z0-9]*)$/', \App\Handlers\PagesHandler, viewWeby] #frontend Weby
    - ['/^([a-z0-9_-]*)\/([a-z0-9]*)$/', \App\Handlers\EditorHandler, route] #backend editor router
    - ['/^([a-z0-9_-]*)$/', \App\Handlers\EditorHandler, route] #backend editor router