routes:
    - ['', \App\Handlers\PagesHandler, index]
    - ['editor', \App\Handlers\EditorHandler, index]
    - [files/upload, \App\Handlers\FilesHandler, upload]
    - [database, \App\Handlers\TestHandler, index]