routes:
    - ['', \App\Handlers\PagesHandler, index]
    - ['editor', \App\Handlers\EditorHandler, index]
    - ['embed/linkedin', \App\Handlers\EmbedHandler, linkedin]
    - ['files/get', \App\Handlers\FilesHandler, getFileInfo]
    - [database, \App\Handlers\TestHandler, index]