routes:
    # SECURITY
    - ['security/check-logged-user', \App\Handlers\UsersHandler, checkUserExists]

    # PUBLIC PAGES
    - ['', \App\Handlers\PagesHandler, index]
    - ['about', \App\Handlers\PagesHandler, about]

    # TOOLS
    - ['tools/webies', \App\Handlers\ToolsHandler, ajaxGetWebies]
    - ['tools/webies/tags', \App\Handlers\ToolsHandler, ajaxGetWebiesByTags] # Gets Webies by tags (used also by WP widget)
    - ['tools/favorites', \App\Handlers\ToolsHandler, ajaxGetFavorites]
    - ['/^tools\/favorite\/([a-z0-9]*)$/', \App\Handlers\ToolsHandler, ajaxToggleFavorite]
    - ['tools/log', \App\Handlers\ToolsHandler, log]
    - ['tools/parse-link', \App\Handlers\LinksHandler, parse]
    - ['/^tools\/delete-weby\/([a-z0-9]*)$/', \App\Handlers\ToolsHandler, deleteWeby]
    - ['/^tools\/take-screenshot\/([a-z0-9]*)$/', \App\Handlers\ToolsHandler, takeScreenshot]
    - ['/^tools\/screenshot\/([a-z0-9]*)$/', \App\Handlers\ToolsHandler, viewWeby] # render Weby for screenshot

    # EDITOR
    - ['editor/save', \App\Handlers\EditorHandler, save]
    - ['editor/create', \App\Handlers\EditorHandler, create]
    - ['editor/dashboard', \App\Handlers\EditorHandler, dashboard]
    - ['editor/upload-image', \App\Handlers\EditorHandler, uploadImage]
    - ['editor/remove-image', \App\Handlers\EditorHandler, removeImage]
    - ['user/intro-done', \App\Handlers\UsersHandler, markIntroductionDone]

    # EMBED
    - ['embed/linkedin', \App\Handlers\EmbedHandler, linkedin]
    - ['embed/vine', \App\Handlers\EmbedHandler, vine]
    - ['embed/pinterest', \App\Handlers\EmbedHandler, pinterest]
    - ['embed/fb-post', \App\Handlers\EmbedHandler, fbPost]

    # CRON ROUTES
    - ['cron/inactive-users', \App\Handlers\CronHandler, checkInactiveUsers]

    # STATS ROUTES
    - ['stats', \App\Handlers\StatsHandler, index]
    - ['stats/ajax-get-week-stats', \App\Handlers\StatsHandler, ajaxGetWeekStats]
    - ['stats/ajax-get-month-stats', \App\Handlers\StatsHandler, ajaxGetMonthStats]
    - ['stats/ajax-get-year-stats', \App\Handlers\StatsHandler, ajaxGetYearStats]
    - ['stats/ajax-get-stats', \App\Handlers\StatsHandler, ajaxGetStats]
    - ['stats/ajax-get-widget-usage-stats', \App\Handlers\StatsHandler, ajaxGetWidgetUsageStats]
    - ['stats/ajax-get-top-users-stats', \App\Handlers\StatsHandler, ajaxGetTopUsersStats]
    - ['stats/ajax-get-top-webies-stats', \App\Handlers\StatsHandler, ajaxGetTopWebiesStats]
    - ['stats/ajax-get-active-users-stats', \App\Handlers\StatsHandler, ajaxGetActiveUsersStats]

    # GLOBAL ROUTES
    - ['/^([a-z0-9_-]*)\/([a-z0-9_-]*)\/([a-z0-9]*)$/', \App\Handlers\PagesHandler, viewWeby] #frontend Weby
    - ['/^([a-z0-9_-]*)\/([a-z0-9]*)$/', \App\Handlers\EditorHandler, route] #backend editor router
    - ['/^([a-z0-9_-]*)$/', \App\Handlers\EditorHandler, route] #backend editor router